<?php

igk_wln("the view not changed....");
include(dirname(__FILE__)."/.header.pinc");

$bootstrap = igk_require_module("bootstrap", false);

$doc->Title = "WIKI - cancaseditor";

$t->clearChilds();
$t->setClass("google-Roboto");
$t->addDiv();

$t->addJumbotron();
 

$d = $t->addDiv();
$c = $d->addContainer();







//+ Footer
$d = $t->addDiv();
$c = $d->addContainer();
$c->addSingleRowCol()->addDiv()->addIGKCopyRight();



