<?php
if (!file_exists(dirname(__FILE__)."/cancaseditor/default.phtml"))
	return;
 

$ctn =$t->addDiv()->addContainer();
$dv = $ctn->addRow()->addCol()->addDiv();

$dv->addSectionTitle(4)->Content = "Cancas Editor";
$dv = $ctn->addRow()->addCol();
igk_html_article($this, "cancaseditor.presentation",$dv->addDiv());


$ctn->addRow()->addCol()->addDiv()->addA($this->getAppUri("cancaseditor"))->Content = R::gets("Open");
