<?php
if (empty($uri = igk_ctrl_get_app_uri(app_balafon::class))){
	return;
}

$ctn = $t->addDiv()->addContainer();
$row = $ctn->addRow();
$dv = $row->addCol()->addDiv();
$dv->addSectionTitle(4)->Content = "Balafon";
$row = $ctn->addRow();
$c = $row->addCol()->addDiv();
$c->addArticle($this, "balafon.presentation.template", []);
// igk_html_article($this, "balafon.presentation", $c);
