<?php
use function igk_resources_gets as __; //language resolution 


//char not allowed on name
 // igk_wln("data" , igk_sys_getconfig("mail_contact"));
 // igk_wln_e("data" , igk_mail_noreply_address());

igk_reg_hook(IGKEvents::HOOK_HTML_META, function(){
	echo "<meta name='igk-app-version' content='igkdev2.0' />";
});
igk_doc_set_favicon($doc, $this->getResourcesDir()."/Img/favicon.ico");
$t->clearChilds();

 
  
igk_view_handle_actions($fname, ["update"=>
function()use($ctrl){
	/*/igk_wln("update-------------------------%>");//*/
	igk_navto($ctrl->getAppUri());
	igk_exit();
}, 
"contactme"=>function(){
	if (!igk_environment()->is("POST") && !igk_html_valid_cref(1)){
		return;
	}
	extract(igk_getr_kv(["firstname"=>"","lastname"=>"", "email"=>"", "message"=>""]));
 
	$error = [];
	//
	// validation 
	//
	if(!IGKValidator::IsEmail($email)) $error['email'] = "email not valid";
	if (empty($message) || (strlen($message)>200)) $error['message'] = "message not valid";
	
	// validate the name - 
	if (strpos($firstname, ".") !==false)$error['firstname'] = "firstname not valid";
	if (strpos($lastname, ".") !==false)$error['lastname'] = "lastname not valid";
	
	
	if (count($error) == 0){
			if(igk_mail_sendmail(
				igk_sys_getconfig("mail_contact"), 
				igk_mail_noreply_address(),
				"Subject : Contact-Me",
				$message)){
				igk_resetr();
				igk_notifyctrl("mailcontact")->addMsg("Thank you for your");
		}else{
			
		igk_notifyctrl("mailcontact")->addError("Error: mail not send");
		}
	} else {
		igk_notifyctrl("mailcontact")->addError("Error: contact form not valid");
	}
	
	igk_ajx_replace_uri($this->getAppUri("#contact_form"));
},
"(@error)"=>[
	403=>function($uri=null){
		igk_wln_e("access denied");		
		igk_exit();
	},
	404=>function($uri=null){
	
	
	if (preg_match("/\.json$/", $uri)){
		igk_header_set_contenttype("json");		
		echo json_encode(array("error"=>1, "uri"=>$uri, "msg"=>$this->name." : resources not found")); //  "{'error':'1', 'msg':'file not found}";
		igk_exit();
	}	
	igk_set_header(404);
	igk_reg_hook(IGKEvents::HOOK_HTML_HEAD, function(){
		?><!DOCTYPE Html><html><head><title>ERROR 404</title></head><body><?php
	});	
	igk_reg_hook(IGKEvents::HOOK_HTML_FOOTER, function(){
		?></body></html><?php
	});
	$this->loader->view("error/404", ['uri'=>$uri]); 
	igk_wl($this->_output);		
	igk_exit();
}]], $params); 



//add egede meta compatibility - igk_doc_add_ie_meta_compatibility
// $meta =  igk_createnode("meta");
// $meta["http-equiv"] = "X-UA-Compatible";
// $meta[IGKHtmlMetaManager::ATTR_CONTENT]="IE=edge";
// $doc->Metas->addMeta("X-UA-Compatible-Edge", $meta);
// igk_ilog("clear theme:".igk_io_request_uri()." ".($c = igk_env_count(__FILE__)));
// igk_io_w2file("d:\\temp\\trace".$c.".html", igk_ob_get_func("igk_trace"));

$doc->theme->def->clear(); 
$t->clearChilds();
$t->addJSLogger(true);
$t->addDiv()->addContainer()->addSingleRowCol("fitw")->addDiv()->setClass("cookie-warn alignm")->addArticle($this, "cookie.warn"); 
// $t->addObData(function(){
	// $this->loader->view(IGK_LIB_DIR."/Articles/templates/page_template.phtml", array(
	// "docType"=>"html",
	// "title"=>"Base",
	// "currentLang"=>R::GetCurrentLang()
	// ),1);
	// echo "done".$this->loader->getOut(). " finishi ";
// });

// $t->RenderAJX();
// echo json_encode($_SESSION);
// igk_exit();
//return; 

include_once($dir."/.header.pinc");
$t["class"]="+google-Roboto";
// $body = $t->addSingleNodeViewer("NoTagNode")->targetNode;

// $t->addScript()->Content = <<<EOF

// function loaddata(uri, t){
// 	igk.system.io.getData(uri, function(d){
// 		console.debug(d);
// 		t.setHtml("data load :"+d.data);
// 	}, 'text/plain');
// }

// EOF;


//$t->addDiv()->on["ready"]="loaddata('https://fonts.googleapis.com/css?family=Roboto:100;200;400;700;900',this)";
// igk_wln("invoke view....".__FILE__);


// if (igk_io_request_for_firefox_thumbnails()){
	// $doc->body["class"]= "+custom-thumbnail";
	// include_once($dir."/{$fname}.thumbnail.phtml");
	// return;
// } 
$doc->Title = "IGKDEV"; 
$t->addNotifyHost();


// igk_wl(igk_html_eval_article(
// IGKCtrlTypeBase::GetAdditionalDefaultViewContent(), [
// "author"=>igk_sys_getconfig("developer", IGK_AUTHOR), 
// "date"=>date("Y-m-d H:i:s"),
// "version"=>1.0,
// ]));
// igk_wl(IGKCtrlTypeBase::GetAdditionalDefaultViewContent());
// exit;

 



 
 //$t->addDiv()->setId('font')->setContent("Font Family")->on["click"] = "igk.log.write(\$igk(this).getComputedStyle('font-family'));";
 //$t->addDiv()->setId('font')->setContent("Font face")->on["ready"] = "igk.log.write(FontFace)";
  
 $frm = $t->addForm(); 
 
 // $frm["action"] = $this->getAppUri($fname."/update"); 
 // $frm->addInput("clH", "text", "Hola ...."); 
 // $frm->addButton("btone", "submit")->Content = "Click here";
 
 
 $d = $t->addDiv()->setClass("igk-h-section"); 
 //title
 $container = $d->addDiv()->setClass('igk-header')->addContainer();
 $d= $container->addRow()->addCol()->addDiv();
 $d->addDiv()->setClass("igk-title-4 ft-think no-padding google-Roboto")->setContent("IGKDEV");
 $d->add("span")->setClass("igk-css-def igk-hbox igk-smaller")->setContent("{Believe in IT Solutions}"); 
 
  $vd = $t->addDiv();//->setClass("no-overflow");  
 
 //CSS Strick : white-space: nowrap; //for single line
 
 
 // $vd->addDiv()
 // ->setClass("igkdev-bg-layout no-print off-comment")
 // ->setAttribute("igk-node-disable-selection", 1)
 // ->addRepeatContent(5)->addDiv()->Content =<<<EOF
// IGKDEV \033 C.A.D. BONDJE DOUE, COMPUTER, DEVELOPER, ANALYST, IT, BALAFON, DRSSTUDIO, IGKGLLIB, WEBSITE, MVET, SNACK, C/C++, C#, PHP, C#, JAVASCRIPT, HTML5, CSS3, UML, OPENGL, JBGAME,ANDROID, IGKCoreLib
// EOF; 
$dv =  $vd->addDiv()->addContainer();
igk_hook(IGKEvents::HOOK_APP_PRESENTATION, [$this, $dv]);

igk_ctrl_view_load_pattern($this, $dv, "app");

$dv = $t->addDiv()->setClass("contact")->setStyle("margin-top: 2em;");
$cn = $dv->addContainer();

$frm = $cn->addSingleRowCol("igk-col-3-3 alignc")->addForm();
$frm["action"] = $this->getAppUri($fname."/contactme");
$frm["class"] = "contact_form alignl dispib";
// $frm["onsubmit"] = "javascript: return false;";
$frm->setId("contact_form");
$frm->addNotifyHost("mailcontact");

$frm->addDiv()->setClass("alignc")->setStyle("margin-bottom: 3em")->addSectionTitle(4)->Content = __("Contact Us");

igk_html_form_initfield($frm);
igk_html_form_buildformfield($frm, [
	"firstname"=>["attribs"=>["maxlength"=>20, "placeholder"=>__("firstname") ], "label_text"=>__("firstname")],
	"lastname"=>["attribs"=>["maxlength"=>40, "placeholder"=>__("lastname")], "label_text"=>__("lastname")],
	"email"=>["type"=>"email", "placeholder"=>"your mail", "attribs"=>["maxlength"=>60],"label_text"=>__("email")], 
	"message"=>["type"=>"textarea", "attribs"=>["maxlength"=>200], "label_text"=>__("message")]
]);
$c = $frm->addDiv()->setClass("action-bar");
$c->addLabel()->setContent("");
$c->addButton("btn.send")->setAttribute("type", "submit")->setContent(__("Send"));

include(dirname(__FILE__)."/.footer.pinc");
unset($body);