<?php
// svg demonstration
$s = <<<EOF
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="16" height="16" id="LayerDocument_37907746" viewBox="0 0 16 16" fill="#FFF" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<rect id="Rectangle_42446399" x="0" y="0" width="14" height="13" fill="#FF5300" stroke="#0083FF" stroke-linejoin="round" stroke-miterlimit="0" stroke-width="1" />
</svg>
EOF;
// igk_wl(base64_encode(str_replace("#", "%23", $s)));
igk_wl(base64_encode($s)); //str_replace("#", "%23", $s)));
igk_exit();
