<p>
Documentation : 
</p>


le présent document de liscence et condition d'utilisation peut être modifier sans préavis. 

comment obtenir le Code source?

il suffit juste de vous sur la plateform 

vous obiendrais alors le lien qui vous permettra de telecharger le code source.

boite à message:

deposer ici vous remarques, critiques et suggestion.

une erreur est survenu pendant l'utilisation de application!!!! 
signaler le . Nous corrigerons le problèmes et et version plus à jours sera disposible pour la communauté.

