<div>
Voici , elle est là la librarie BALAFON
qui comprend est une suite logiciel dédier à la création d'interface 
Web Riche, Responsive et Dynamique.

<p>
Telecharger sans plus attendre la version gratuite et eprouver là

<quote>
</quote>
</p>

<p class="dispn">
Mes Remerciements vont à tous ceux qui m'on soutenu de près ou de loin à la réalisation 
de se Projet. En particulier, mon Dieu qui malgré les souffrances ne m'a jamais 
abandonné, à ma Maman qui m'a donnée la vie.
</p>

Nous vous souhaitons un bon amusement avec cette plateforme dont le nom "BALAFON" fait référence 
à cet instrument de musique qui appel au rassemblement.


<igk:panel igk:Style="default">
Rassemblons nous dérrière cette plateforme et reppoussons les limites du development WEB.
</igk:panel>
</div>